# Generated by Django 6.0 on 2026-02-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_volunteerapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerApplication',
            new_name='VolunteerProfile',
        ),
    ]
