# Generated by Django 6.0 on 2026-02-08 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Amount in smallest currency unit (e.g., cents)')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(help_text='Donation status (pending, succeeded, failed)', max_length=50)),
                ('payment_processor', models.CharField(default='stripe', max_length=50)),
                ('processor_reference_id', models.CharField(help_text='PaymentIntent or transaction ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.event')),
                ('person', models.ForeignKey(blank=True, help_text='Null for anonymous donations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.person')),
            ],
        ),
    ]
