# Generated by Django 6.0 on 2026-02-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to news article (e.g., LMT Online) or Facebook post', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
